#!/bin/bash

echo "Aggiornamento Sistema Operativo"
apt-get update -q=2 && apt-get dist-upgrade -y -q=2 && apt-get autoremove -y -q=2

echo "Installazione Database Postgresql"
sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
apt-get update -q=2
apt-get upgrade -y -q=2
apt-get install -y -q=2 postgresql-9.4 pgadmin3

echo "Installazione pacchetti deb"
apt-get install -y mc zip unzip htop ntp ghostscript graphviz antiword git libpq-dev poppler-utils python-pip build-essential libfreetype6-dev npm python-magic python-dateutil python-pypdf python-requests \
python-feedparser python-gdata python-ldap python-libxslt1 python-lxml python-mako python-openid python-psycopg2 python-pybabel python-pychart python-pydot python-pyparsing python-reportlab python-simplejson \
python-tz python-vatnumber python-vobject python-webdav python-werkzeug python-xlwt python-yaml python-zsi python-docutils python-psutil python-unittest2 python-mock python-jinja2 python-dev \
python-pdftools python-decorator python-openssl python-babel python-imaging python-reportlab-accel python-paramiko python-cups python-software-properties python-pip python-dev build-essential libpq-dev \
poppler-utils antiword libldap2-dev libsasl2-dev libssl-dev git python-dateutil python-feedparser python-gdata python-ldap python-lxml python-mako python-openid python-psycopg2 python-pychart python-pydot \
python-pyparsing python-reportlab python-tz python-vatnumber python-vobject python-webdav python-xlwt python-yaml python-zsi python-docutils python-unittest2 python-mock python-jinja2 libevent-dev libxslt1-dev \
libfreetype6-dev libjpeg8-dev python-werkzeug wkhtmltopdf libjpeg-dev pgtune python-setuptools python-genshi python-cairo python-lxml libreoffice libreoffice-script-provider-python python3-pip nginx munin apache2-utils

echo "Installazione pacchetti pip"
pip install passlib beautifulsoup4 evdev reportlab qrcode polib unidecode validate_email pyDNS pysftp python-slugify phonenumbers py-Asterisk codicefiscale unicodecsv ofxparse pytils gevent_psycopg2 psycogreen erppeek PyXB

echo "Installazione pacchetti npm"
npm install -g less less-plugin-clean-css
ln -s /usr/bin/nodejs /usr/bin/node

echo "Installazione Barcodes"
wget --quiet http://www.reportlab.com/ftp/pfbfer.zip
unzip pfbfer.zip -d fonts
mv fonts /usr/lib/python2.7/dist-packages/reportlab/
rm pfbfer.zip

echo "Installazione wkhtmltox 0.12.1"
wget --quiet http://www.openerp24.de/fileadmin/content/dateien/wkhtmltox-0.12.1_linux-trusty-amd64.deb
dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
rm wkhtmltox-0.12.1_linux-trusty-amd64.deb

echo "Installazione PoS"
pip install pyserial
pip install --pre pyusb

echo "Ottimizzazione configurazione database"
pgtune -i /etc/postgresql/9.4/main/postgresql.conf -o /etc/postgresql/9.4/main/postgresql.conf.tuned
mv /etc/postgresql/9.4/main/postgresql.conf  /etc/postgresql/9.4/main/postgresql.conf.old
mv /etc/postgresql/9.4/main/postgresql.conf.tuned  /etc/postgresql/9.4/main/postgresql.conf
/etc/init.d/postgresql stop
/etc/init.d/postgresql start 
cat /etc/postgresql/9.4/main/postgresql.conf

echo "Installazione AerooLib"
mkdir /opt/aeroo
git clone https://github.com/aeroo/aeroolib.git /opt/aeroo/aeroolib
cd /opt/aeroo/aeroolib
python setup.py install
cd
echo '#!/bin/sh' > /etc/init.d/office
echo '' >> /etc/init.d/office
echo '/usr/bin/soffice --nologo --nofirststartwizard --headless --norestore --invisible "--accept=socket,host=localhost,port=8100,tcpNoDelay=1;urp;" &'  >> /etc/init.d/office
chmod +x /etc/init.d/office
update-rc.d office defaults
/etc/init.d/office
pip3 install jsonrpc2 daemonize
git clone https://github.com/aeroo/aeroo_docs.git /opt/aeroo/aeroo_docs
cd /opt/aeroo/aeroo_docs/
echo "Y" | python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf
ln -s /opt/aeroo/aeroo_docs/aeroo-docs /etc/init.d/aeroo-docs
update-rc.d aeroo-docs defaults


echo "Installazione Odoo 8.0"
adduser odoo --system --group --shell /bin/bash --home /opt/odoo
sudo -u postgres createuser -s odoo
sudo -u postgres psql -c "ALTER USER odoo WITH PASSWORD 'odoo';"
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'odoo';"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/OCB.git /opt/odoo/OCB"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/webkit-tools /opt/odoo/source/OCA/webkit-tools"
su - odoo -c "mkdir -p /opt/odoo/addons"
su - odoo -c "ln -s /opt/odoo/source/OCA/webkit-tools/base_headers_webkit /opt/odoo/addons/base_headers_webkit"
su - odoo -c "ln -s /opt/odoo/source/OCA/webkit-tools/report_webkit_chapter_server /opt/odoo/addons/report_webkit_chapter_server"
su - odoo -c "mkdir -p /opt/odoo/source/aeroo"
su - odoo -c "git clone -b master https://github.com/aeroo/aeroo_reports.git /opt/odoo/source/aeroo/aeroo_reports"
su - odoo -c "ln -s /opt/odoo/source/aeroo/aeroo_reports/report_aeroo /opt/odoo/addons/report_aeroo"
su - odoo -c "ln -s /opt/odoo/source/aeroo/aeroo_reports/report_aeroo_controller /opt/odoo/addons/report_aeroo_controller"
su - odoo -c "ln -s /opt/odoo/source/aeroo/aeroo_reports/report_aeroo_direct_print /opt/odoo/addons/report_aeroo_direct_print"
su - odoo -c "ln -s /opt/odoo/source/aeroo/aeroo_reports/report_aeroo_printscreen /opt/odoo/addons/report_aeroo_printscreen"
su - odoo -c "ln -s /opt/odoo/source/aeroo/aeroo_reports/report_aeroo_sample /opt/odoo/addons/report_aeroo_sample"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/reporting-engine /opt/odoo/source/OCA/reporting-engine"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/base_report_assembler /opt/odoo/addons/base_report_assembler"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/report_custom_filename /opt/odoo/addons/report_custom_filename"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/report_qweb_element_page_visibility /opt/odoo/addons/report_qweb_element_page_visibility"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/report_qweb_signer /opt/odoo/addons/report_qweb_signer"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/report_xls /opt/odoo/addons/report_xls"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/report_xml /opt/odoo/addons/report_xml"
su - odoo -c "ln -s /opt/odoo/source/OCA/reporting-engine/report_xml_sample /opt/odoo/addons/report_xml_sample"
su - odoo -c "sed -i "s/admin/odoo/g" /opt/odoo/server/openerp/tools/config.py"
su - odoo -c "cp /opt/odoo/OCB/addons/web/static/src/img/favicon.ico /opt/odoo/" 
sed -i "s/'auto_install': True/'auto_install': False/" /opt/odoo/OCB/addons/im_odoo_support/__openerp__.py
sudo chown -R odoo:odoo /opt/odoo/server
sudo chown -R odoo:odoo /opt/odoo
mkdir /var/log/odoo
chown odoo:odoo /var/log/odoo
cp /opt/odoo/OCB/debian/logrotate /etc/logrotate.d/odoo-server
chmod 755 /etc/logrotate.d/odoo-server
wget https://raw.githubusercontent.com/fcoach66/odoo-install/master/openerp.init.d -O /etc/init.d/odoo-server
sudo chmod +x /etc/init.d/odoo-server
sudo update-rc.d odoo-server defaults
su - odoo -c "mkdir -p /opt/odoo/addons"
su - odoo -c "/opt/odoo/OCB/odoo.py --stop-after-init -s -c /opt/odoo/odoo.conf --db_host=localhost --db_user=odoo --db_password=False --workers=9 --addons-path=/opt/odoo/OCB/openerp/addons,/opt/odoo/OCB/addons,/opt/odoo/addons --logfile=/var/log/odoo/odoo-server.log"
mv /opt/odoo/odoo.conf /etc/odoo-server.conf
chown odoo:odoo /etc/odoo-server.conf
sed -i "s/db_password = False/db_password = odoo/g" /etc/odoo-server.conf
wget https://raw.githubusercontent.com/fcoach66/odoo-install/master/odoo.nginx -O /etc/nginx/sites-available/odoo.nginx
rm /etc/nginx/sites-enabled/default 
ln -s /etc/nginx/sites-available/odoo.nginx /etc/nginx/sites-enabled/odoo.nginx
# old1="xmlrpc_interface = "
# new1="xmlrpc_interface = 127.0.0.1"
# old2="netrpc_interface = "
# new2="netrpc_interface = 127.0.0.1"
# sed -i "s/$old1/$new1/g" /etc/odoo-server.conf
# sed -i "s/$old2/$new2/g" /etc/odoo-server.conf
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
wget https://raw.githubusercontent.com/fcoach66/odoo-install/master/nginx.conf -O /etc/nginx/nginx.conf
htpasswd -cb /etc/nginx/htpasswd odoo odoo

echo "Installazione Odoo 8.0 moduli l10n-italy"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/l10n-italy /opt/odoo/source/OCA/l10n-italy"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/account_central_journal /opt/odoo/addons/account_central_journal"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/account_fiscal_year_closing /opt/odoo/addons/account_fiscal_year_closing"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/account_invoice_entry_date /opt/odoo/addons/account_invoice_entry_date"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/account_invoice_sequential_dates /opt/odoo/addons/account_invoice_sequential_dates"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/account_vat_period_end_statement /opt/odoo/addons/account_vat_period_end_statement"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_abicab /opt/odoo/addons/l10n_it_abicab"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_account /opt/odoo/addons/l10n_it_account"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_ateco /opt/odoo/addons/l10n_it_ateco"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_base /opt/odoo/addons/l10n_it_base"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_base_crm /opt/odoo/addons/l10n_it_base_crm"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_base_location_geonames_import /opt/odoo/addons/l10n_it_base_location_geonames_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_bill_of_entry /opt/odoo/addons/l10n_it_bill_of_entry"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_CEE_balance_generic /opt/odoo/addons/l10n_it_CEE_balance_generic"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_corrispettivi /opt/odoo/addons/l10n_it_corrispettivi"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_ddt /opt/odoo/addons/l10n_it_ddt"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_DDT_webkit /opt/odoo/addons/l10n_it_DDT_webkit"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_fatturapa /opt/odoo/addons/l10n_it_fatturapa"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_fatturapa_out /opt/odoo/addons/l10n_it_fatturapa_out"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_fiscalcode /opt/odoo/addons/l10n_it_fiscalcode"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_ipa /opt/odoo/addons/l10n_it_ipa"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_partially_deductible_vat /opt/odoo/addons/l10n_it_partially_deductible_vat"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_pec /opt/odoo/addons/l10n_it_pec"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_prima_nota_cassa /opt/odoo/addons/l10n_it_prima_nota_cassa"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_rea /opt/odoo/addons/l10n_it_rea"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_ricevute_bancarie /opt/odoo/addons/l10n_it_ricevute_bancarie"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_sale /opt/odoo/addons/l10n_it_sale"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_split_payment /opt/odoo/addons/l10n_it_split_payment"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_vat_registries /opt/odoo/addons/l10n_it_vat_registries"
su - odoo -c "ln -s /opt/odoo/source/OCA/l10n-italy/l10n_it_withholding_tax /opt/odoo/addons/l10n_it_withholding_tax"


echo "Installazione Odoo 8.0 moduli partner-contact"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/partner-contact /opt/odoo/source/OCA/partner-contact"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/account_partner_merge /opt/odoo/addons/account_partner_merge"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_contact /opt/odoo/addons/base_contact"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_continent /opt/odoo/addons/base_continent"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_location /opt/odoo/addons/base_location"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_location_geonames_import /opt/odoo/addons/base_location_geonames_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_location_nuts /opt/odoo/addons/base_location_nuts"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_partner_merge /opt/odoo/addons/base_partner_merge"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/base_partner_sequence /opt/odoo/addons/base_partner_sequence"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/firstname_display_name_trigger /opt/odoo/addons/firstname_display_name_trigger"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_academic_title /opt/odoo/addons/partner_academic_title"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_address_street3 /opt/odoo/addons/partner_address_street3"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_auto_salesman /opt/odoo/addons/partner_auto_salesman"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_capital /opt/odoo/addons/partner_capital"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_address_detailed /opt/odoo/addons/partner_contact_address_detailed"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_birthdate /opt/odoo/addons/partner_contact_birthdate"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_department /opt/odoo/addons/partner_contact_department"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_gender /opt/odoo/addons/partner_contact_gender"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_in_several_companies /opt/odoo/addons/partner_contact_in_several_companies"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_job_position /opt/odoo/addons/partner_contact_job_position"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_nationality /opt/odoo/addons/partner_contact_nationality"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_contact_personal_information_page /opt/odoo/addons/partner_contact_personal_information_page"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_employee_quantity /opt/odoo/addons/partner_employee_quantity"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_external_maps /opt/odoo/addons/partner_external_maps"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_firstname /opt/odoo/addons/partner_firstname"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_helper /opt/odoo/addons/partner_helper"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_relations /opt/odoo/addons/partner_relations"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_second_lastname /opt/odoo/addons/partner_second_lastname"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_sector /opt/odoo/addons/partner_sector"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/partner_street_number /opt/odoo/addons/partner_street_number"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/passport /opt/odoo/addons/passport"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/portal_partner_merge /opt/odoo/addons/portal_partner_merge"
su - odoo -c "ln -s /opt/odoo/source/OCA/partner-contact/res_partner_affiliate /opt/odoo/addons/res_partner_affiliate"


echo "Installazione Odoo 8.0 moduli account-payment"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/account-payment /opt/odoo/source/OCA/account-payment"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_due_list /opt/odoo/addons/account_due_list"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_due_list_payment_mode /opt/odoo/addons/account_due_list_payment_mode"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_payment_extension /opt/odoo/addons/account_payment_extension"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_payment_order_to_voucher /opt/odoo/addons/account_payment_order_to_voucher"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_payment_term_multi_day /opt/odoo/addons/account_payment_term_multi_day"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_vat_on_payment /opt/odoo/addons/account_vat_on_payment"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_voucher_cash_basis /opt/odoo/addons/account_voucher_cash_basis"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_voucher_display_writeoff /opt/odoo/addons/account_voucher_display_writeoff"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_voucher_supplier_invoice_number /opt/odoo/addons/account_voucher_supplier_invoice_number"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/account_voucher_tax_filter /opt/odoo/addons/account_voucher_tax_filter"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/nan_account_bank_statement /opt/odoo/addons/nan_account_bank_statement"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/oca_dependencies.txt /opt/odoo/addons/oca_dependencies.txt"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/purchase_payment /opt/odoo/addons/purchase_payment"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/pxgo_bank_statement_analytic /opt/odoo/addons/pxgo_bank_statement_analytic"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/pxgo_bank_statement_running_balance /opt/odoo/addons/pxgo_bank_statement_running_balance"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/pxgo_cash_statement /opt/odoo/addons/pxgo_cash_statement"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-payment/sale_payment /opt/odoo/addons/sale_payment"


echo "Installazione Odoo 8.0 moduli bank-payment"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/bank-payment /opt/odoo/source/OCA/bank-payment"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking /opt/odoo/addons/account_banking"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_mandate /opt/odoo/addons/account_banking_mandate"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_pain_base /opt/odoo/addons/account_banking_pain_base"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_payment_export /opt/odoo/addons/account_banking_payment_export"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_payment_transfer /opt/odoo/addons/account_banking_payment_transfer"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_sepa_credit_transfer /opt/odoo/addons/account_banking_sepa_credit_transfer"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_sepa_direct_debit /opt/odoo/addons/account_banking_sepa_direct_debit"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_banking_tests /opt/odoo/addons/account_banking_tests"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_direct_debit /opt/odoo/addons/account_direct_debit"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_import_line_multicurrency_extension /opt/odoo/addons/account_import_line_multicurrency_extension"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_blocking /opt/odoo/addons/account_payment_blocking"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_include_draft_move /opt/odoo/addons/account_payment_include_draft_move"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_mode_term /opt/odoo/addons/account_payment_mode_term"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_partner /opt/odoo/addons/account_payment_partner"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_purchase /opt/odoo/addons/account_payment_purchase"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_sale /opt/odoo/addons/account_payment_sale"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_payment_sale_stock /opt/odoo/addons/account_payment_sale_stock"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/account_voucher_killer /opt/odoo/addons/account_voucher_killer"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-payment/bank_statement_instant_voucher /opt/odoo/addons/bank_statement_instant_voucher"


echo "Installazione Odoo 8.0 moduli stock-logistics-workflow"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/stock-logistics-workflow /opt/odoo/source/OCA/stock-logistics-workflow"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/picking_dispatch /opt/odoo/addons/picking_dispatch"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/picking_dispatch_wave /opt/odoo/addons/picking_dispatch_wave"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/product_customer_code_picking /opt/odoo/addons/product_customer_code_picking"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/product_serial /opt/odoo/addons/product_serial"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/product_unique_serial /opt/odoo/addons/product_unique_serial"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_cancel /opt/odoo/addons/stock_cancel"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_dropshipping_dual_invoice /opt/odoo/addons/stock_dropshipping_dual_invoice"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_filter_none_zero_qty /opt/odoo/addons/stock_filter_none_zero_qty"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_inventory_retry_assign /opt/odoo/addons/stock_inventory_retry_assign"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_location_flow_creator /opt/odoo/addons/stock_location_flow_creator"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_move_backdating /opt/odoo/addons/stock_move_backdating"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_move_description /opt/odoo/addons/stock_move_description"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_move_on_hold /opt/odoo/addons/stock_move_on_hold"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_no_negative /opt/odoo/addons/stock_no_negative"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_obsolete /opt/odoo/addons/stock_obsolete"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_ownership_availability_rules /opt/odoo/addons/stock_ownership_availability_rules"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_ownership_by_move /opt/odoo/addons/stock_ownership_by_move"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_backorder_strategy /opt/odoo/addons/stock_picking_backorder_strategy"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_compute_delivery_date /opt/odoo/addons/stock_picking_compute_delivery_date"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_deliver_uos /opt/odoo/addons/stock_picking_deliver_uos"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_invoice_link /opt/odoo/addons/stock_picking_invoice_link"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_mass_assign /opt/odoo/addons/stock_picking_mass_assign"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_package_preparation /opt/odoo/addons/stock_picking_package_preparation"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_package_preparation_line /opt/odoo/addons/stock_picking_package_preparation_line"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_priority /opt/odoo/addons/stock_picking_priority"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_reorder_lines /opt/odoo/addons/stock_picking_reorder_lines"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_picking_show_returns /opt/odoo/addons/stock_picking_show_returns"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_sale_filters /opt/odoo/addons/stock_sale_filters"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_split_picking /opt/odoo/addons/stock_split_picking"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-workflow/stock_transfer_split_multi /opt/odoo/addons/stock_transfer_split_multi"


echo "Installazione Odoo 8.0 moduli product-attribute"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/product-attribute /opt/odoo/source/OCA/product-attribute"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/base_custom_attributes /opt/odoo/addons/base_custom_attributes"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/customer_context_in_product_view /opt/odoo/addons/customer_context_in_product_view"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/partner_custom_attributes /opt/odoo/addons/partner_custom_attributes"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_attribute_multi_type /opt/odoo/addons/product_attribute_multi_type"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_brand /opt/odoo/addons/product_brand"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_catalog_report /opt/odoo/addons/product_catalog_report"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_categ_attributes /opt/odoo/addons/product_categ_attributes"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_custom_attributes /opt/odoo/addons/product_custom_attributes"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_customer_code /opt/odoo/addons/product_customer_code"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_dimension /opt/odoo/addons/product_dimension"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_electronic /opt/odoo/addons/product_electronic"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_gift /opt/odoo/addons/product_gift"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_gtin /opt/odoo/addons/product_gtin"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_icecat /opt/odoo/addons/product_icecat"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_images /opt/odoo/addons/product_images"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_index /opt/odoo/addons/product_index"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/production_lot_custom_attributes /opt/odoo/addons/production_lot_custom_attributes"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_listprice_upgrade /opt/odoo/addons/product_listprice_upgrade"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_lot_foundry /opt/odoo/addons/product_lot_foundry"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_m2mcategories /opt/odoo/addons/product_m2mcategories"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_manufacturer /opt/odoo/addons/product_manufacturer"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_multi_price /opt/odoo/addons/product_multi_price"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_pricelist_fixed_price /opt/odoo/addons/product_pricelist_fixed_price"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_prices_on_variant /opt/odoo/addons/product_prices_on_variant"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_profile /opt/odoo/addons/product_profile"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_profile_example /opt/odoo/addons/product_profile_example"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_qt /opt/odoo/addons/product_qt"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_quick_stock_rule /opt/odoo/addons/product_quick_stock_rule"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_search_reference /opt/odoo/addons/product_search_reference"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_sequence /opt/odoo/addons/product_sequence"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_series /opt/odoo/addons/product_series"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_size /opt/odoo/addons/product_size"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_supplierinfo_for_customer /opt/odoo/addons/product_supplierinfo_for_customer"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_supplierinfo_tree_price_info /opt/odoo/addons/product_supplierinfo_tree_price_info"
su - odoo -c "ln -s /opt/odoo/source/OCA/product-attribute/product_weight /opt/odoo/addons/product_weight"


echo "Installazione Odoo 8.0 moduli stock-logistics-warehouse"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/stock-logistics-warehouse /opt/odoo/source/OCA/stock-logistics-warehouse"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/base_product_merge /opt/odoo/addons/base_product_merge"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/configurable_stock_level /opt/odoo/addons/configurable_stock_level"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_available /opt/odoo/addons/stock_available"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_available_immediately /opt/odoo/addons/stock_available_immediately"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_available_mrp /opt/odoo/addons/stock_available_mrp"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_available_sale /opt/odoo/addons/stock_available_sale"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_inventory_preparation_filter /opt/odoo/addons/stock_inventory_preparation_filter"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_location_area_data /opt/odoo/addons/stock_location_area_data"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_location_area_management /opt/odoo/addons/stock_location_area_management"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_location_ownership /opt/odoo/addons/stock_location_ownership"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_lot_valuation /opt/odoo/addons/stock_lot_valuation"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_move_location /opt/odoo/addons/stock_move_location"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_mts_mto_rule /opt/odoo/addons/stock_mts_mto_rule"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_optional_valuation /opt/odoo/addons/stock_optional_valuation"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_orderpoint_creator /opt/odoo/addons/stock_orderpoint_creator"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_quant_manual_assign /opt/odoo/addons/stock_quant_manual_assign"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_quant_merge /opt/odoo/addons/stock_quant_merge"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_reord_rule /opt/odoo/addons/stock_reord_rule"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_reserve /opt/odoo/addons/stock_reserve"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-warehouse/stock_reserve_sale /opt/odoo/addons/stock_reserve_sale"


echo "Installazione Odoo 8.0 moduli stock-logistics-tracking"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/stock-logistics-tracking /opt/odoo/source/OCA/stock-logistics-tracking"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_barcode_reader /opt/odoo/addons/stock_barcode_reader"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_inventory_sequence /opt/odoo/addons/stock_inventory_sequence"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_move_packaging /opt/odoo/addons/stock_move_packaging"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_move_split_default /opt/odoo/addons/stock_move_split_default"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_packaging_usability /opt/odoo/addons/stock_packaging_usability"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_packaging_usability_ul /opt/odoo/addons/stock_packaging_usability_ul"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_product_category_tracked /opt/odoo/addons/stock_product_category_tracked"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_add_move /opt/odoo/addons/stock_tracking_add_move"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_add_remove /opt/odoo/addons/stock_tracking_add_remove"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_add_remove_pack /opt/odoo/addons/stock_tracking_add_remove_pack"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_child /opt/odoo/addons/stock_tracking_child"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_extended /opt/odoo/addons/stock_tracking_extended"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_prodlot /opt/odoo/addons/stock_tracking_prodlot"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_reopen /opt/odoo/addons/stock_tracking_reopen"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_state /opt/odoo/addons/stock_tracking_state"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_swap /opt/odoo/addons/stock_tracking_swap"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-tracking/stock_tracking_swap_pack /opt/odoo/addons/stock_tracking_swap_pack"


echo "Installazione Odoo 8.0 moduli stock-logistics-barcode"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 https://github.com/OCA/stock-logistics-barcode /opt/odoo/source/OCA/stock-logistics-barcode"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/barcode_link /opt/odoo/addons/barcode_link"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/base_gs1_barcode /opt/odoo/addons/base_gs1_barcode"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/product_barcode_generator /opt/odoo/addons/product_barcode_generator"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/product_multi_ean /opt/odoo/addons/product_multi_ean"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode /opt/odoo/addons/tr_barcode"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode_config /opt/odoo/addons/tr_barcode_config"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode_field /opt/odoo/addons/tr_barcode_field"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode_on_picking /opt/odoo/addons/tr_barcode_on_picking"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode_on_prodlots /opt/odoo/addons/tr_barcode_on_prodlots"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode_on_product /opt/odoo/addons/tr_barcode_on_product"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-barcode/tr_barcode_on_tracking /opt/odoo/addons/tr_barcode_on_tracking"


echo "Installazione Odoo 8.0 modulo l10n-italy l10n_it_withholding_tax"
su - odoo -c "mkdir -p /opt/odoo/source/elbati"
su - odoo -c "git clone -b porting_withholding_tax_8 --single-branch https://github.com/eLBati/l10n-italy /opt/odoo/source/elbati/l10n-italy-withholding_tax"

echo "Installazione Odoo 8.0 moduli yelizariev addons-yelizariev"
su - odoo -c "git clone -b 8.0 --single-branch  https://github.com/yelizariev/addons-yelizariev /opt/odoo/source/yelizariev/addons-yelizariev"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/access_base /opt/odoo/addons/access_base"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/access_custom /opt/odoo/addons/access_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/access_custom2 /opt/odoo/addons/access_custom2"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/autostaging_base /opt/odoo/addons/autostaging_base"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/autostaging_project_task /opt/odoo/addons/autostaging_project_task"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/base_replace_ref /opt/odoo/addons/base_replace_ref"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/booking_calendar /opt/odoo/addons/booking_calendar"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/booking_calendar_analytic /opt/odoo/addons/booking_calendar_analytic"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/contract_purchases /opt/odoo/addons/contract_purchases"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/crm_expected_revenue /opt/odoo/addons/crm_expected_revenue"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/crm_next_action /opt/odoo/addons/crm_next_action"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/crm_phonecall_notification /opt/odoo/addons/crm_phonecall_notification"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/currency_rate_update /opt/odoo/addons/currency_rate_update"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/custom_menu_bar /opt/odoo/addons/custom_menu_bar"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/delivery_sequence /opt/odoo/addons/delivery_sequence"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/delivery_special /opt/odoo/addons/delivery_special"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/fleet_odometer_oil /opt/odoo/addons/fleet_odometer_oil"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/fleet_odometer_track_changes /opt/odoo/addons/fleet_odometer_track_changes"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/gamification_extra /opt/odoo/addons/gamification_extra"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/group_menu_no_access /opt/odoo/addons/group_menu_no_access"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/im_notif /opt/odoo/addons/im_notif"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/import_csv_fix_field_limit /opt/odoo/addons/import_csv_fix_field_limit"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/import_custom /opt/odoo/addons/import_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/import_framework /opt/odoo/addons/import_framework"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/ir_attachment_force_storage /opt/odoo/addons/ir_attachment_force_storage"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/ir_sequence_autoreset /opt/odoo/addons/ir_sequence_autoreset"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/is_employee /opt/odoo/addons/is_employee"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/itprojects_sale /opt/odoo/addons/itprojects_sale"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/itprojects_website /opt/odoo/addons/itprojects_website"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/labels /opt/odoo/addons/labels"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/labels_custom /opt/odoo/addons/labels_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_check_immediately /opt/odoo/addons/mail_check_immediately"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_delete_access_link /opt/odoo/addons/mail_delete_access_link"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_delete_odoo_footer /opt/odoo/addons/mail_delete_odoo_footer"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_delete_sent_by_footer /opt/odoo/addons/mail_delete_sent_by_footer"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_fix_553 /opt/odoo/addons/mail_fix_553"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_fix_empty_body /opt/odoo/addons/mail_fix_empty_body"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_fix_header_from /opt/odoo/addons/mail_fix_header_from"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_move_message /opt/odoo/addons/mail_move_message"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_outgoing /opt/odoo/addons/mail_outgoing"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_partner_lang /opt/odoo/addons/mail_partner_lang"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_recovery /opt/odoo/addons/mail_recovery"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_sent /opt/odoo/addons/mail_sent"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_todo_custom /opt/odoo/addons/mail_todo_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_wall_custom /opt/odoo/addons/mail_wall_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_wall_menu /opt/odoo/addons/mail_wall_menu"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mail_wall_widgets /opt/odoo/addons/mail_wall_widgets"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mass_mailing_extra /opt/odoo/addons/mass_mailing_extra"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/money_for /opt/odoo/addons/money_for"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mrp_custom /opt/odoo/addons/mrp_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mrp_loaner /opt/odoo/addons/mrp_loaner"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mrp_repair_custom /opt/odoo/addons/mrp_repair_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/mrp_repair_default_name /opt/odoo/addons/mrp_repair_default_name"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/multi_company_extra /opt/odoo/addons/multi_company_extra"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/phonecall_repair_order /opt/odoo/addons/phonecall_repair_order"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/pitch_booking /opt/odoo/addons/pitch_booking"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/product_custom /opt/odoo/addons/product_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/product_image_filestore /opt/odoo/addons/product_image_filestore"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/product_tags /opt/odoo/addons/product_tags"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/product_without_taxes /opt/odoo/addons/product_without_taxes"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/project_default_visibility_followers /opt/odoo/addons/project_default_visibility_followers"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/project_description /opt/odoo/addons/project_description"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/project_kanban_customer /opt/odoo/addons/project_kanban_customer"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/project_tags /opt/odoo/addons/project_tags"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/project_task_auto_staging /opt/odoo/addons/project_task_auto_staging"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/reminder_base /opt/odoo/addons/reminder_base"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/reminder_crm_next_action /opt/odoo/addons/reminder_crm_next_action"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/reminder_hr_recruitment /opt/odoo/addons/reminder_hr_recruitment"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/reminder_issue_deadline /opt/odoo/addons/reminder_issue_deadline"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/reminder_phonecall /opt/odoo/addons/reminder_phonecall"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/reminder_task_deadline /opt/odoo/addons/reminder_task_deadline"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_bank_sort_code /opt/odoo/addons/res_partner_bank_sort_code"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_bank_swift /opt/odoo/addons/res_partner_bank_swift"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_company_click_contacts /opt/odoo/addons/res_partner_company_click_contacts"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_company_messages /opt/odoo/addons/res_partner_company_messages"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_company_name /opt/odoo/addons/res_partner_company_name"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_company_search /opt/odoo/addons/res_partner_company_search"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_company_stat /opt/odoo/addons/res_partner_company_stat"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_country_code /opt/odoo/addons/res_partner_country_code"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_phone /opt/odoo/addons/res_partner_phone"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_ru /opt/odoo/addons/res_partner_ru"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_skype /opt/odoo/addons/res_partner_skype"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_strip_email /opt/odoo/addons/res_partner_strip_email"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_strip_name /opt/odoo/addons/res_partner_strip_name"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_partner_vk /opt/odoo/addons/res_partner_vk"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_users_clear_access_rights /opt/odoo/addons/res_users_clear_access_rights"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_users_default_company /opt/odoo/addons/res_users_default_company"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_users_hide_suggestions /opt/odoo/addons/res_users_hide_suggestions"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_users_signature /opt/odoo/addons/res_users_signature"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/res_users_signature_hr /opt/odoo/addons/res_users_signature_hr"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_contract_slots /opt/odoo/addons/sale_contract_slots"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_disable_send_quotation /opt/odoo/addons/sale_disable_send_quotation"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_mediation /opt/odoo/addons/sale_mediation"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_mediation_custom /opt/odoo/addons/sale_mediation_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_order_created /opt/odoo/addons/sale_order_created"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_order_hide_tax /opt/odoo/addons/sale_order_hide_tax"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_report_kz /opt/odoo/addons/sale_report_kz"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_report_lt /opt/odoo/addons/sale_report_lt"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sale_report_ru /opt/odoo/addons/sale_report_ru"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sms_sg /opt/odoo/addons/sms_sg"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/sugarcrm_migration /opt/odoo/addons/sugarcrm_migration"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/thecage_data /opt/odoo/addons/thecage_data"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/translate_website_description /opt/odoo/addons/translate_website_description"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_calendar_quick_navigation /opt/odoo/addons/web_calendar_quick_navigation"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_calendar_repeat_form /opt/odoo/addons/web_calendar_repeat_form"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_char_domain /opt/odoo/addons/web_char_domain"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_debranding /opt/odoo/addons/web_debranding"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_debranding_support /opt/odoo/addons/web_debranding_support"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_iframe /opt/odoo/addons/web_iframe"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_iframe_pages /opt/odoo/addons/web_iframe_pages"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/_web_last_viewed_records /opt/odoo/addons/_web_last_viewed_records"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_logo /opt/odoo/addons/web_logo"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_polymorphic_field /opt/odoo/addons/web_polymorphic_field"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/addons-yelizariev/web_sessions_management /opt/odoo/addons/web_sessions_management"


echo "Installazione Odoo 8.0 moduli yelizariev pos-addons"
su - odoo -c "git clone -b 8.0 --single-branch  https://github.com/yelizariev/pos-addons /opt/odoo/source/yelizariev/pos-addons"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/_chricar_product_gtin /opt/odoo/addons/_chricar_product_gtin"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_debranding /opt/odoo/addons/pos_debranding"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_debt_notebook /opt/odoo/addons/pos_debt_notebook"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_details_custom /opt/odoo/addons/pos_details_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_disable_payment /opt/odoo/addons/pos_disable_payment"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_discount_total /opt/odoo/addons/pos_discount_total"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_keyboard /opt/odoo/addons/pos_keyboard"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_multi_session /opt/odoo/addons/pos_multi_session"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_product_available /opt/odoo/addons/pos_product_available"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_product_lot /opt/odoo/addons/pos_product_lot"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_sale_order /opt/odoo/addons/pos_sale_order"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_scan_ref /opt/odoo/addons/pos_scan_ref"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_session_custom /opt/odoo/addons/pos_session_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_session_custom2 /opt/odoo/addons/pos_session_custom2"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_ticket_custom /opt/odoo/addons/pos_ticket_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/pos_ticket_custom2 /opt/odoo/addons/pos_ticket_custom2"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/_product_barcode_generator /opt/odoo/addons/_product_barcode_generator"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/product_barcode_generator_custom /opt/odoo/addons/product_barcode_generator_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/product_brand /opt/odoo/addons/product_brand"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/product_lot /opt/odoo/addons/product_lot"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/product_variant_multi /opt/odoo/addons/product_variant_multi"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/tg_partner_firstname /opt/odoo/addons/tg_partner_firstname"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/tg_pos_debt_notebook /opt/odoo/addons/tg_pos_debt_notebook"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/tg_pos_enhanced /opt/odoo/addons/tg_pos_enhanced"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/tg_pos_message /opt/odoo/addons/tg_pos_message"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/pos-addons/tg_pos_packs /opt/odoo/addons/tg_pos_packs"


echo "Installazione Odoo 8.0 moduli yelizariev website-addons"
su - odoo -c "git clone -b 8.0 --single-branch  https://github.com/yelizariev/website-addons /opt/odoo/source/yelizariev/website-addons"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/web_login_background /opt/odoo/addons/web_login_background"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_booking_calendar /opt/odoo/addons/website_booking_calendar"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_crm_sales_team /opt/odoo/addons/website_crm_sales_team"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_custom /opt/odoo/addons/website_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_debranding /opt/odoo/addons/website_debranding"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_files /opt/odoo/addons/website_files"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_forum_faq_edit /opt/odoo/addons/website_forum_faq_edit"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_login_background /opt/odoo/addons/website_login_background"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_proposal /opt/odoo/addons/website_proposal"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_proposal_lead /opt/odoo/addons/website_proposal_lead"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_redirect /opt/odoo/addons/website_redirect"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_add_to_cart /opt/odoo/addons/website_sale_add_to_cart"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_add_to_cart_stock_status /opt/odoo/addons/website_sale_add_to_cart_stock_status"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_auto_confirm_order /opt/odoo/addons/website_sale_auto_confirm_order"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_autopay /opt/odoo/addons/website_sale_autopay"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_available /opt/odoo/addons/website_sale_available"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_available_fake /opt/odoo/addons/website_sale_available_fake"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_birthdate /opt/odoo/addons/website_sale_birthdate"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_clear_cart /opt/odoo/addons/website_sale_clear_cart"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_order /opt/odoo/addons/website_sale_order"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_product_tags /opt/odoo/addons/website_sale_product_tags"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_search_custom /opt/odoo/addons/website_sale_search_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_special_offer /opt/odoo/addons/website_sale_special_offer"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sales_team /opt/odoo/addons/website_sales_team"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sales_team_custom /opt/odoo/addons/website_sales_team_custom"
su - odoo -c "ln -s /opt/odoo/source/yelizariev/website-addons/website_sale_stock_status /opt/odoo/addons/website_sale_stock_status"


echo "Installazione Odoo 8.0 moduli sale-workflow"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/sale-workflow /opt/odoo/source/OCA/sale-workflow"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/account_invoice_reorder_lines /opt/odoo/addons/account_invoice_reorder_lines"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/mail_quotation /opt/odoo/addons/mail_quotation"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/partner_prepayment /opt/odoo/addons/partner_prepayment"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/partner_prospect /opt/odoo/addons/partner_prospect"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/pricelist_share_companies /opt/odoo/addons/pricelist_share_companies"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/product_customer_code_sale /opt/odoo/addons/product_customer_code_sale"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/product_special_type /opt/odoo/addons/product_special_type"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/product_special_type_invoice /opt/odoo/addons/product_special_type_invoice"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/product_special_type_sale /opt/odoo/addons/product_special_type_sale"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_automatic_workflow /opt/odoo/addons/sale_automatic_workflow"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_automatic_workflow_exception /opt/odoo/addons/sale_automatic_workflow_exception"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_cancel_reason /opt/odoo/addons/sale_cancel_reason"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_condition_text /opt/odoo/addons/sale_condition_text"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_delivery_term /opt/odoo/addons/sale_delivery_term"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_dropshipping /opt/odoo/addons/sale_dropshipping"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_exception_nostock /opt/odoo/addons/sale_exception_nostock"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_exceptions /opt/odoo/addons/sale_exceptions"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_fiscal_position_update /opt/odoo/addons/sale_fiscal_position_update"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_jit_on_services /opt/odoo/addons/sale_jit_on_services"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_journal_shop /opt/odoo/addons/sale_journal_shop"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_last_price_info /opt/odoo/addons/sale_last_price_info"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_multi_picking /opt/odoo/addons/sale_multi_picking"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_add_variants /opt/odoo/addons/sale_order_add_variants"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_back2draft /opt/odoo/addons/sale_order_back2draft"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_force_number /opt/odoo/addons/sale_order_force_number"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_line_description /opt/odoo/addons/sale_order_line_description"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_price_recalculation /opt/odoo/addons/sale_order_price_recalculation"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_revision /opt/odoo/addons/sale_order_revision"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_order_type /opt/odoo/addons/sale_order_type"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_owner_stock_sourcing /opt/odoo/addons/sale_owner_stock_sourcing"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_packaging_price /opt/odoo/addons/sale_packaging_price"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_partner_incoterm /opt/odoo/addons/sale_partner_incoterm"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_partner_order_policy /opt/odoo/addons/sale_partner_order_policy"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_payment_method /opt/odoo/addons/sale_payment_method"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_payment_method_automatic_workflow /opt/odoo/addons/sale_payment_method_automatic_workflow"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_payment_method_transaction_id /opt/odoo/addons/sale_payment_method_transaction_id"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_payment_term_interest /opt/odoo/addons/sale_payment_term_interest"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_pricelist_discount /opt/odoo/addons/sale_pricelist_discount"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_procurement_group_by_line /opt/odoo/addons/sale_procurement_group_by_line"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_product_set /opt/odoo/addons/sale_product_set"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_product_set_layout /opt/odoo/addons/sale_product_set_layout"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_properties_dynamic_fields /opt/odoo/addons/sale_properties_dynamic_fields"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_properties_easy_creation /opt/odoo/addons/sale_properties_easy_creation"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_quotation_number /opt/odoo/addons/sale_quotation_number"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_quotation_sourcing /opt/odoo/addons/sale_quotation_sourcing"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_quotation_sourcing_stock_route_transit /opt/odoo/addons/sale_quotation_sourcing_stock_route_transit"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_reason_to_export /opt/odoo/addons/sale_reason_to_export"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_rental /opt/odoo/addons/sale_rental"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_sourced_by_line /opt/odoo/addons/sale_sourced_by_line"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_sourced_by_line_sale_transport_multi_address /opt/odoo/addons/sale_sourced_by_line_sale_transport_multi_address"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_start_end_dates /opt/odoo/addons/sale_start_end_dates"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_stock_global_delivery_lead_time /opt/odoo/addons/sale_stock_global_delivery_lead_time"
su - odoo -c "ln -s /opt/odoo/source/OCA/sale-workflow/sale_validity /opt/odoo/addons/sale_validity"


echo "Installazione Odoo 8.0 moduli stock-logistics-transport"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/stock-logistics-transport /opt/odoo/source/OCA/stock-logistics-transport"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/purchase_requisition_transport_multi_address /opt/odoo/addons/purchase_requisition_transport_multi_address"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/purchase_transport_multi_address /opt/odoo/addons/purchase_transport_multi_address"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/sale_transport_multi_address /opt/odoo/addons/sale_transport_multi_address"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/stock_route_transit /opt/odoo/addons/stock_route_transit"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/stock_shipment_management /opt/odoo/addons/stock_shipment_management"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/stock_transport_multi_address /opt/odoo/addons/stock_transport_multi_address"
su - odoo -c "ln -s /opt/odoo/source/OCA/stock-logistics-transport/transport_information /opt/odoo/addons/transport_information"


echo "Installazione Odoo 8.0 moduli account-closing"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/account-closing /opt/odoo/source/OCA/account-closing"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-closing/account_cutoff_accrual_base /opt/odoo/addons/account_cutoff_accrual_base"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-closing/account_cutoff_accrual_picking /opt/odoo/addons/account_cutoff_accrual_picking"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-closing/account_cutoff_base /opt/odoo/addons/account_cutoff_base"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-closing/account_cutoff_prepaid /opt/odoo/addons/account_cutoff_prepaid"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-closing/account_multicurrency_revaluation /opt/odoo/addons/account_multicurrency_revaluation"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-closing/account_multicurrency_revaluation_report /opt/odoo/addons/account_multicurrency_revaluation_report"


echo "Installazione Odoo 8.0 moduli server-tools"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/server-tools /opt/odoo/source/OCA/server-tools"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/admin_technical_features /opt/odoo/addons/admin_technical_features"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auditlog /opt/odoo/addons/auditlog"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_admin_passkey /opt/odoo/addons/auth_admin_passkey"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_dynamic_groups /opt/odoo/addons/auth_dynamic_groups"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_from_http_basic /opt/odoo/addons/auth_from_http_basic"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_from_http_basic_logout /opt/odoo/addons/auth_from_http_basic_logout"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_from_http_remote_user /opt/odoo/addons/auth_from_http_remote_user"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_signup_verify_email /opt/odoo/addons/auth_signup_verify_email"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/auth_supplier /opt/odoo/addons/auth_supplier"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_concurrency /opt/odoo/addons/base_concurrency"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_debug4all /opt/odoo/addons/base_debug4all"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_export_manager /opt/odoo/addons/base_export_manager"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_external_dbsource /opt/odoo/addons/base_external_dbsource"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_field_serialized /opt/odoo/addons/base_field_serialized"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_module_doc_rst /opt/odoo/addons/base_module_doc_rst"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_optional_quick_create /opt/odoo/addons/base_optional_quick_create"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_report_auto_create_qweb /opt/odoo/addons/base_report_auto_create_qweb"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_suspend_security /opt/odoo/addons/base_suspend_security"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_user_gravatar /opt/odoo/addons/base_user_gravatar"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/base_user_reset_access /opt/odoo/addons/base_user_reset_access"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/configuration_helper /opt/odoo/addons/configuration_helper"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/cron_run_manually /opt/odoo/addons/cron_run_manually"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/database_cleanup /opt/odoo/addons/database_cleanup"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/datetime_formatter /opt/odoo/addons/datetime_formatter"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/dbfilter_from_header /opt/odoo/addons/dbfilter_from_header"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/dead_mans_switch_client /opt/odoo/addons/dead_mans_switch_client"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/dead_mans_switch_server /opt/odoo/addons/dead_mans_switch_server"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/disable_openerp_online /opt/odoo/addons/disable_openerp_online"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/email_template_template /opt/odoo/addons/email_template_template"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/fetchmail_attach_from_folder /opt/odoo/addons/fetchmail_attach_from_folder"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/fetchmail_notify_error_to_sender /opt/odoo/addons/fetchmail_notify_error_to_sender"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/import_odbc /opt/odoo/addons/import_odbc"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/inactive_session_timeout /opt/odoo/addons/inactive_session_timeout"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/ir_config_parameter_viewer /opt/odoo/addons/ir_config_parameter_viewer"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/language_path_mixin /opt/odoo/addons/language_path_mixin"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/log_forwarded_for_ip /opt/odoo/addons/log_forwarded_for_ip"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/mail_environment /opt/odoo/addons/mail_environment"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/mass_editing /opt/odoo/addons/mass_editing"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/module_prototyper /opt/odoo/addons/module_prototyper"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/qweb_usertime /opt/odoo/addons/qweb_usertime"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/scheduler_error_mailer /opt/odoo/addons/scheduler_error_mailer"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/security_protector /opt/odoo/addons/security_protector"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/server_env_base_external_referentials /opt/odoo/addons/server_env_base_external_referentials"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/server_environment /opt/odoo/addons/server_environment"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/server_environment_files_sample /opt/odoo/addons/server_environment_files_sample"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/shell /opt/odoo/addons/shell"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/super_calendar /opt/odoo/addons/super_calendar"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/users_ldap_groups /opt/odoo/addons/users_ldap_groups"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/users_ldap_mail /opt/odoo/addons/users_ldap_mail"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/users_ldap_populate /opt/odoo/addons/users_ldap_populate"
su - odoo -c "ln -s /opt/odoo/source/OCA/server-tools/web_context_tunnel /opt/odoo/addons/web_context_tunnel"


echo "Installazione Odoo 8.0 moduli account-financial-tools"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/account-financial-tools /opt/odoo/source/OCA/account-financial-tools"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_asset_management /opt/odoo/addons/account_asset_management"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_asset_management_xls /opt/odoo/addons/account_asset_management_xls"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_auto_fy_sequence /opt/odoo/addons/account_auto_fy_sequence"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_balance_line /opt/odoo/addons/account_balance_line"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_cancel_invoice_check_payment_order /opt/odoo/addons/account_cancel_invoice_check_payment_order"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_cancel_invoice_check_voucher /opt/odoo/addons/account_cancel_invoice_check_voucher"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_chart_update /opt/odoo/addons/account_chart_update"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_check_deposit /opt/odoo/addons/account_check_deposit"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_compute_tax_amount /opt/odoo/addons/account_compute_tax_amount"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_constraints /opt/odoo/addons/account_constraints"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_credit_control /opt/odoo/addons/account_credit_control"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_credit_control_dunning_fees /opt/odoo/addons/account_credit_control_dunning_fees"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_default_draft_move /opt/odoo/addons/account_default_draft_move"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_fiscal_position_vat_check /opt/odoo/addons/account_fiscal_position_vat_check"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_invoice_constraint_chronology /opt/odoo/addons/account_invoice_constraint_chronology"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_invoice_currency /opt/odoo/addons/account_invoice_currency"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_invoice_tax_required /opt/odoo/addons/account_invoice_tax_required"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_journal_always_check_date /opt/odoo/addons/account_journal_always_check_date"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_journal_period_close /opt/odoo/addons/account_journal_period_close"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_move_batch_validate /opt/odoo/addons/account_move_batch_validate"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_move_line_no_default_search /opt/odoo/addons/account_move_line_no_default_search"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_move_line_payable_receivable_filter /opt/odoo/addons/account_move_line_payable_receivable_filter"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_move_line_search_extension /opt/odoo/addons/account_move_line_search_extension"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_move_locking /opt/odoo/addons/account_move_locking"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_move_template /opt/odoo/addons/account_move_template"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_netting /opt/odoo/addons/account_netting"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_partner_required /opt/odoo/addons/account_partner_required"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_renumber /opt/odoo/addons/account_renumber"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_reset_chart /opt/odoo/addons/account_reset_chart"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_reversal /opt/odoo/addons/account_reversal"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_tax_analysis /opt/odoo/addons/account_tax_analysis"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_tax_chart_interval /opt/odoo/addons/account_tax_chart_interval"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/account_tax_update /opt/odoo/addons/account_tax_update"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/async_move_line_importer /opt/odoo/addons/async_move_line_importer"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/currency_rate_date_check /opt/odoo/addons/currency_rate_date_check"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-tools/currency_rate_update /opt/odoo/addons/currency_rate_update"


echo "Installazione Odoo 8.0 moduli connector"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/connector /opt/odoo/source/OCA/connector"
su - odoo -c "ln -s /opt/odoo/source/OCA/connector/connector /opt/odoo/addons/connector"
su - odoo -c "ln -s /opt/odoo/source/OCA/connector/connector_base_product /opt/odoo/addons/connector_base_product"


echo "Installazione Odoo 8.0 moduli account-financial-reporting"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/account-financial-reporting /opt/odoo/source/OCA/account-financial-reporting"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_chart_report /opt/odoo/addons/account_chart_report"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_export_csv /opt/odoo/addons/account_export_csv"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_financial_report /opt/odoo/addons/account_financial_report"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_financial_report_horizontal /opt/odoo/addons/account_financial_report_horizontal"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_financial_report_webkit /opt/odoo/addons/account_financial_report_webkit"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_financial_report_webkit_xls /opt/odoo/addons/account_financial_report_webkit_xls"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_journal_report_xls /opt/odoo/addons/account_journal_report_xls"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_move_line_report_xls /opt/odoo/addons/account_move_line_report_xls"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/account_tax_report_no_zeroes /opt/odoo/addons/account_tax_report_no_zeroes"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/mis_builder /opt/odoo/addons/mis_builder"
su - odoo -c "ln -s /opt/odoo/source/OCA/account-financial-reporting/mis_builder_demo /opt/odoo/addons/mis_builder_demo"


echo "Installazione Odoo 8.0 moduli bank-statement-reconcile"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/bank-statement-reconcile /opt/odoo/source/OCA/bank-statement-reconcile"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_advanced_reconcile /opt/odoo/addons/account_advanced_reconcile"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_advanced_reconcile_bank_statement /opt/odoo/addons/account_advanced_reconcile_bank_statement"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_advanced_reconcile_transaction_ref /opt/odoo/addons/account_advanced_reconcile_transaction_ref"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_bank_statement_period_from_line_date /opt/odoo/addons/account_bank_statement_period_from_line_date"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_easy_reconcile /opt/odoo/addons/account_easy_reconcile"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_invoice_reference /opt/odoo/addons/account_invoice_reference"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_payment_transaction_id /opt/odoo/addons/account_payment_transaction_id"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_reconcile_payment_order /opt/odoo/addons/account_reconcile_payment_order"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_bankaccount_completion /opt/odoo/addons/account_statement_bankaccount_completion"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_base_completion /opt/odoo/addons/account_statement_base_completion"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_base_import /opt/odoo/addons/account_statement_base_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_cancel_line /opt/odoo/addons/account_statement_cancel_line"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_commission /opt/odoo/addons/account_statement_commission"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_completion_label /opt/odoo/addons/account_statement_completion_label"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_completion_voucher /opt/odoo/addons/account_statement_completion_voucher"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_ext /opt/odoo/addons/account_statement_ext"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_ext_point_of_sale /opt/odoo/addons/account_statement_ext_point_of_sale"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_ext_voucher /opt/odoo/addons/account_statement_ext_voucher"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_no_invoice_import /opt/odoo/addons/account_statement_no_invoice_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_ofx_import /opt/odoo/addons/account_statement_ofx_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_one_move /opt/odoo/addons/account_statement_one_move"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_operation_multicompany /opt/odoo/addons/account_statement_operation_multicompany"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_regex_account_completion /opt/odoo/addons/account_statement_regex_account_completion"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_so_completion /opt/odoo/addons/account_statement_so_completion"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_transactionid_completion /opt/odoo/addons/account_statement_transactionid_completion"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/account_statement_transactionid_import /opt/odoo/addons/account_statement_transactionid_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-reconcile/base_transaction_id /opt/odoo/addons/base_transaction_id"


echo "Installazione Odoo 8.0 moduli bank-statement-import"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/bank-statement-import /opt/odoo/source/OCA/bank-statement-import"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import /opt/odoo/addons/account_bank_statement_import"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_camt /opt/odoo/addons/account_bank_statement_import_camt"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_mt940_base /opt/odoo/addons/account_bank_statement_import_mt940_base"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_mt940_nl_ing /opt/odoo/addons/account_bank_statement_import_mt940_nl_ing"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_mt940_nl_rabo /opt/odoo/addons/account_bank_statement_import_mt940_nl_rabo"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_ofx /opt/odoo/addons/account_bank_statement_import_ofx"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_qif /opt/odoo/addons/account_bank_statement_import_qif"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/account_bank_statement_import_save_file /opt/odoo/addons/account_bank_statement_import_save_file"
su - odoo -c "ln -s /opt/odoo/source/OCA/bank-statement-import/base_bank_account_number_unique /opt/odoo/addons/base_bank_account_number_unique"


echo "Installazione Odoo 8.0 moduli rma"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/rma /opt/odoo/source/OCA/rma"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_claim_categ_as_name /opt/odoo/addons/crm_claim_categ_as_name"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_claim_ext /opt/odoo/addons/crm_claim_ext"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_claim_product_supplier /opt/odoo/addons/crm_claim_product_supplier"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_claim_rma /opt/odoo/addons/crm_claim_rma"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_claim_rma_code /opt/odoo/addons/crm_claim_rma_code"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_rma_by_shop /opt/odoo/addons/crm_rma_by_shop"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_rma_location /opt/odoo/addons/crm_rma_location"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_rma_lot_mass_return /opt/odoo/addons/crm_rma_lot_mass_return"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_rma_prodlot_invoice /opt/odoo/addons/crm_rma_prodlot_invoice"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_rma_prodlot_supplier /opt/odoo/addons/crm_rma_prodlot_supplier"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/crm_rma_stock_location /opt/odoo/addons/crm_rma_stock_location"
su - odoo -c "ln -s /opt/odoo/source/OCA/rma/product_warranty /opt/odoo/addons/product_warranty"


echo "Installazione Odoo 8.0 moduli crm"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/crm /opt/odoo/source/OCA/crm"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_action /opt/odoo/addons/crm_action"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_claim_code /opt/odoo/addons/crm_claim_code"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_claim_type /opt/odoo/addons/crm_claim_type"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_address_street3 /opt/odoo/addons/crm_lead_address_street3"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_code /opt/odoo/addons/crm_lead_code"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_invoice_address /opt/odoo/addons/crm_lead_invoice_address"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_lost_reason /opt/odoo/addons/crm_lead_lost_reason"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_sale_link /opt/odoo/addons/crm_lead_sale_link"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_stage_monitoring /opt/odoo/addons/crm_lead_stage_monitoring"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_supplier /opt/odoo/addons/crm_lead_supplier"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_vat /opt/odoo/addons/crm_lead_vat"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_lead_website /opt/odoo/addons/crm_lead_website"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_location /opt/odoo/addons/crm_location"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_sector /opt/odoo/addons/crm_sector"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/crm_track_next_action /opt/odoo/addons/crm_track_next_action"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/lettermgmt /opt/odoo/addons/lettermgmt"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/lettermgmt_hr /opt/odoo/addons/lettermgmt_hr"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/mass_mailing_partner /opt/odoo/addons/mass_mailing_partner"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/newsletter /opt/odoo/addons/newsletter"
su - odoo -c "ln -s /opt/odoo/source/OCA/crm/partner_withdrawal /opt/odoo/addons/partner_withdrawal"


echo "Installazione Odoo 8.0 moduli web"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/web /opt/odoo/source/OCA/web"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/help_online /opt/odoo/addons/help_online"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/help_popup /opt/odoo/addons/help_popup"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/support_branding /opt/odoo/addons/support_branding"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_action_conditionable /opt/odoo/addons/web_action_conditionable"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_advanced_search_x2x /opt/odoo/addons/web_advanced_search_x2x"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_ckeditor4 /opt/odoo/addons/web_ckeditor4"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_clean_navbar /opt/odoo/addons/web_clean_navbar"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_color /opt/odoo/addons/web_color"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_confirm_window_close /opt/odoo/addons/web_confirm_window_close"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_context_in_colors /opt/odoo/addons/web_context_in_colors"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_dashboard_open_action /opt/odoo/addons/web_dashboard_open_action"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_dashboard_tile /opt/odoo/addons/web_dashboard_tile"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_dialog_size /opt/odoo/addons/web_dialog_size"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_dom_model_classes /opt/odoo/addons/web_dom_model_classes"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_easy_switch_company /opt/odoo/addons/web_easy_switch_company"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_environment_ribbon /opt/odoo/addons/web_environment_ribbon"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_export_view /opt/odoo/addons/web_export_view"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_graph_improved /opt/odoo/addons/web_graph_improved"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_group_expand /opt/odoo/addons/web_group_expand"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_hide_db_manager_link /opt/odoo/addons/web_hide_db_manager_link"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_ir_actions_act_window_message /opt/odoo/addons/web_ir_actions_act_window_message"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_ir_actions_act_window_page /opt/odoo/addons/web_ir_actions_act_window_page"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_last_viewed_records /opt/odoo/addons/web_last_viewed_records"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_listview_custom_element_number /opt/odoo/addons/web_listview_custom_element_number"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_m2x_options /opt/odoo/addons/web_m2x_options"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_menu_navbar_needaction /opt/odoo/addons/web_menu_navbar_needaction"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_option_auto_color /opt/odoo/addons/web_option_auto_color"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_polymorphic_many2one /opt/odoo/addons/web_polymorphic_many2one"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_popup_large /opt/odoo/addons/web_popup_large"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_readonly_bypass /opt/odoo/addons/web_readonly_bypass"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_recipients_uncheck /opt/odoo/addons/web_recipients_uncheck"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_search_alphabetic /opt/odoo/addons/web_search_alphabetic"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_searchbar_full_width /opt/odoo/addons/web_searchbar_full_width"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_search_with_and /opt/odoo/addons/web_search_with_and"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_send_message_popup /opt/odoo/addons/web_send_message_popup"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_sheet_full_width /opt/odoo/addons/web_sheet_full_width"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_sheet_full_width_selective /opt/odoo/addons/web_sheet_full_width_selective"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_shortcuts /opt/odoo/addons/web_shortcuts"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_switch_company_warning /opt/odoo/addons/web_switch_company_warning"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_translate_dialog /opt/odoo/addons/web_translate_dialog"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_tree_dynamic_colored_field /opt/odoo/addons/web_tree_dynamic_colored_field"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_tree_image /opt/odoo/addons/web_tree_image"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_tree_many2one_clickable /opt/odoo/addons/web_tree_many2one_clickable"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_widget_color /opt/odoo/addons/web_widget_color"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_widget_datepicker_options /opt/odoo/addons/web_widget_datepicker_options"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_widget_float_formula /opt/odoo/addons/web_widget_float_formula"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_widget_many2many_tags_multi_selection /opt/odoo/addons/web_widget_many2many_tags_multi_selection"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_widget_text_markdown /opt/odoo/addons/web_widget_text_markdown"
su - odoo -c "ln -s /opt/odoo/source/OCA/web/web_widget_x2many_2d_matrix /opt/odoo/addons/web_widget_x2many_2d_matrix"


echo "Installazione Odoo 8.0 moduli project-service"
su - odoo -c "mkdir -p /opt/odoo/source/OCA"
su - odoo -c "git clone -b 8.0 --single-branch https://github.com/OCA/project-service /opt/odoo/source/OCA/project-service"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/account_analytic_analysis_recurring /opt/odoo/addons/account_analytic_analysis_recurring"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/analytic_hours_block /opt/odoo/addons/analytic_hours_block"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_analytic_line_view /opt/odoo/addons/project_analytic_line_view"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_baseuser /opt/odoo/addons/project_baseuser"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_categ /opt/odoo/addons/project_categ"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_categ_issue /opt/odoo/addons/project_categ_issue"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_classification /opt/odoo/addons/project_classification"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_closing /opt/odoo/addons/project_closing"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_description /opt/odoo/addons/project_description"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_functional_block /opt/odoo/addons/project_functional_block"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_gtd /opt/odoo/addons/project_gtd"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_issue_baseuser /opt/odoo/addons/project_issue_baseuser"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_issue_task /opt/odoo/addons/project_issue_task"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_recalculate /opt/odoo/addons/project_recalculate"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_service_type /opt/odoo/addons/project_service_type"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_sla /opt/odoo/addons/project_sla"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_stage_closed /opt/odoo/addons/project_stage_closed"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_stage_state /opt/odoo/addons/project_stage_state"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_stage_state_issue /opt/odoo/addons/project_stage_state_issue"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_task_code /opt/odoo/addons/project_task_code"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_task_materials /opt/odoo/addons/project_task_materials"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_task_materials_stock /opt/odoo/addons/project_task_materials_stock"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/project_timesheet_analytic_partner /opt/odoo/addons/project_timesheet_analytic_partner"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/sale_order_project /opt/odoo/addons/sale_order_project"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/service_desk /opt/odoo/addons/service_desk"
su - odoo -c "ln -s /opt/odoo/source/OCA/project-service/service_desk_issue /opt/odoo/addons/service_desk_issue"


echo "Installazione Odoo 8.0 moduli abstract commission"
su - odoo -c "mkdir -p /opt/odoo/source/abstract-open-solutions"
su - odoo -c "git clone -b 8.0-commission-formula --single-branch https://github.com/abstract-open-solutions/commission /opt/odoo/source/abstract-open-solutions/commission-commission-formula"
su - odoo -c "ln -s /opt/odoo/source/abstract-open-solutions/commission-commission-formula/hr_commission /opt/odoo/addons/hr_commission"
su - odoo -c "ln -s /opt/odoo/source/abstract-open-solutions/commission-commission-formula/sale_commission /opt/odoo/addons/sale_commission"
su - odoo -c "ln -s /opt/odoo/source/abstract-open-solutions/commission-commission-formula/sale_commission_formula /opt/odoo/addons/sale_commission_formula"
su - odoo -c "ln -s /opt/odoo/source/abstract-open-solutions/commission-commission-formula/sale_stock_commission /opt/odoo/addons/sale_stock_commission"


echo "Installazione Odoo 8.0 moduli abstract l10n_it_reverse_charge"
su - odoo -c "mkdir -p /opt/odoo/source/abstract-open-solutions"
su - odoo -c "git clone -b 8.0-reverse-charge --single-branch https://github.com/abstract-open-solutions/l10n-italy /opt/odoo/source/abstract-open-solutions/l10n-italy-reverse-charge"
su - odoo -c "ln -s /opt/odoo/source/abstract-open-solutions/l10n-italy-reverse-charge/l10n_it_reverse_charge /opt/odoo/addons/l10n_it_reverse_charge"

